name: K3s Hardware Runner Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  verify-homelab:
    runs-on: k3s-homelab-pool
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hello World Log
        run: echo "The runner is actively taking action inside your cluster!"